### DISCUSSION TITLE
Monitoring: "No datapoints found"

### DISCUSSION THREAD

**Discussion by smartm0use** [romanz/electrs#831] [General]
I'm running Prometheus for monitoring electrs but going to http://localhost:9090/graph?g0.range_input=1h&g0.expr=index_height&g0.tab=0 (as suggested [here](https://github.com/romanz/electrs/blob/master/doc/monitoring.md)) I get "No datapoints found" error.

What am I doing wrong?

**Comment by romanz** [comment]
It seems that Prometheus doesn't collect electrs' metrics - see https://github.com/romanz/electrs/blob/d128aef758280c7c38f4d89604c66a7e9f6f2135/doc/monitoring.md

**Comment by smartm0use** [comment]
It is what I have done (I also reported that bug in the instructions) but I still get that error.
I'm connecting by remote access using `<node_onion_address>:4224` instead of `localhost:4224`.

Could be this the cause of that error?

**Reply by romanz** [reply]
I don't think... do you see other metrics that prometheus collects by default?
For example: http://localhost:9090/classic/graph?g0.range_input=1h&g0.expr=node_load1&g0.tab=0

**Reply by romanz** [reply]
My bad, see https://github.com/romanz/electrs/discussions/831#discussioncomment-4799345

**Comment by smartm0use** [comment]
It doesn't work, I get the same error.

Here is my configuration at the end of the file located in "/etc/prometheus/prometheus.yml":

```
scrape_configs:
  - job_name: electrs
    static_configs:
      - targets: ['<address>.onion:4224']
```

Any way to check if there are errors in establishing connection to electrs? First time I use Prometheus...

**Reply by romanz** [reply]
Did you restart prometheus (`sudo systemctl restart prometheus`)?

Could you please share your `/etc/prometheus/prometheus.yml`

**Comment by romanz** [comment]
Could you please try using `localhost:4224` to see if it works?

**Comment by smartm0use** [comment]
Sorry, I was wrong, default metrics are working.

Yes, I did restart Prometheus.

Here is the Yml file:

```
# Sample config for Prometheus.

global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'example'

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    scrape_timeout: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    # If prometheus-node-exporter is installed, grab stats about the local
    # machine by default.
    static_configs:
      - targets: ['localhost:9100']

  - job_name: electrs
    static_configs:
      - targets: ['<my-address>.onion:4224']
```

I can't try to use `localhost:4224` because `electrs` in on another machine.
