### ISSUE TITLE
Bug: invalid URL 'http://[fd01::4]:8332': invalid port

### ISSUE THREAD

**Issue by schildbach** [romanz/electrs#792]
**Describe the bug**
If the bitcoind address resolves to an IPv6 address, an invalid URL is being constructed: `http://[fd01::4]:8332`
Either that, or the URL is in fact valid but some component within electrs can't deal with it and outputs the message:

> Bug: invalid URL 'http://[fd01::4]:8332': invalid port

**Electrs version**
electrs 0.9.10 running within Docker 20.10.12 under Ubuntu 22.04.1 LTS (all up to date)

**To Reproduce**
1. Configure and start electrs in an IPv6 network
2. See error, electrs exits with code 1

**Expected behavior**
An IPv6 connection to bitcoind, just like with IPv4.

**Configuration**
The relevant part of the config is probably:
```
    environment:
      - ELECTRS_DAEMON_RPC_ADDR=bitcoind:8332
      - ELECTRS_DAEMON_P2P_ADDR=bitcoind:8333
```

**Comment by schildbach** [comment]
Investigating into the Rust dependency chain, I've stumbled upon these issues:

https://github.com/apoelstra/rust-jsonrpc/issues/62
https://github.com/apoelstra/rust-jsonrpc/pull/63

The line that prints the error message is probably this one:

https://github.com/apoelstra/rust-jsonrpc/blob/master/src/simple_http.rs#L199

I'm still looking into where the "invalid port" reason message is coming from.

**Comment by schildbach** [comment]
It seems like an outdated version of jsonrpc without IPv6 support is being pulled via Cargo dependencies:

```
electrs v0.9.10 (/home/electrs)
├── bitcoincore-rpc v0.16.0
│   ├── jsonrpc v0.12.0
```

jsonrpc 0.13.0 would have IPv6 support – is it possible to overload versions of transitive dependencies with Cargo? Then this would probably be an easy fix.

**Comment by Kixunil** [comment]
It should be possible to patch it - add this to `Cargo.toml`:

```toml
[patch.crates-io.bitcoincore-rpc]
git = "https://github.com/rust-bitcoin/rust-bitcoincore-rpc"
# May minimize the chance of breaking, you can try to leave it out to get even more recent bitcoincore-rpc
branch = "d2959ec11b951f304a538b2bbab67d999cdb3426"
```
