### ISSUE TITLE
Config: Electrs ignores ELECTRS_AUTH enviroment variable

### ISSUE THREAD

**Issue by limpbrains** [romanz/electrs#835]
**Have you read the documentation?**
Yes. 

**How did you configure electrs?**

I'm running `getumbrel/electrs:v0.9.9` and trying to configure electrs to use username and password authentication for bitcoind. But it completely ignores ELECTRS_AUTH env variable, while others are working just fine.

<details>
<summary>docker-compose.yml</summary>

```
version: '3'
services:
  bitcoind:
    restart: unless-stopped
    container_name: btcpayserver_bitcoind
    image: btcpayserver/bitcoin:24.0.1
    environment:
      BITCOIN_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      CREATE_WALLET: 'true'
      BITCOIN_WALLETDIR: '/walletdata'
      BITCOIN_EXTRA_ARGS: |
        rpcport=43782
        rpcbind=0.0.0.0:43782
        rpcallowip=0.0.0.0/0
        port=39388
        whitelist=0.0.0.0/0
        maxmempool=500
        rpcauth=electrumx:7d8ee47c089e6072635f82b34796e878$$13649d99453ccdf78e85007286422599c00e6953289f41bf8e92961076ba14db
        txindex=1
        fallbackfee=0.00001
    expose:
      - '43782'
      - '39388'
    ports:
      - '43782:43782'
      - '39388:39388'
    volumes:
      - './bitcoin_datadir:/data'
      - 'bitcoin_wallet_datadir:/walletdata'

  electrs:
    image: getumbrel/electrs:v0.9.9
    restart: unless-stopped
    depends_on:
      - bitcoind
    expose:
      - '60001'
    ports:
      - '60001:60001'
    volumes:
      - './bitcoin_datadir:/data/.bitcoin'
      - 'electrs_datadir:/data'
    environment:
      - ELECTRS_NETWORK=regtest
      - ELECTRS_ELECTRUM_RPC_ADDR=electrs:60001
      - ELECTRS_DAEMON_RPC_ADDR=bitcoind:43782
      - ELECTRS_DAEMON_P2P_ADDR=bitcoind:39388
      - ELECTRS_LOG_FILTERS=INFO
      - ELECTRS_AUTH=USER:PASSWORD

volumes:
  bitcoin_datadir:
  bitcoin_wallet_datadir:
  electrumx_datadir:
  electrs_datadir:

networks: {}

```

</details>

**Debug output of configuration**
```
tests__-electrs-1      | Starting electrs 0.9.9 on aarch64 linux with Config { network: Regtest, db_path: "./db/regtest", daemon_dir: "/data/.bitcoin/regtest", daemon_auth: CookieFile("/data/.bitcoin/regtest/.cookie"), daemon_rpc_addr: 172.19.0.2:43782, daemon_p2p_addr: 172.19.0.2:39388, electrum_rpc_addr: 172.19.0.3:60001, monitoring_addr: 127.0.0.1:24224, wait_duration: 10s, jsonrpc_timeout: 15s, index_batch_size: 10, index_lookup_limit: None, reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, disable_electrum_rpc: false, server_banner: "Welcome to electrs 0.9.9 (Electrum Rust Server)!", args: [] }
tests__-electrs-1      | [2023-02-01T14:08:20.218Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:24224
tests__-electrs-1      | [2023-02-01T14:08:20.218Z INFO  electrs::server] serving Electrum RPC on 172.19.0.3:60001
tests__-electrs-1      | [2023-02-01T14:08:20.254Z INFO  electrs::db] "./db/regtest": 0 SST files, 0 GB, 0 Grows
tests__-electrs-1      | [2023-02-01T14:08:20.260Z INFO  electrs::daemon] waiting for 0 blocks to download (IBD)
```

**Expected behavior**
It would be nice to be able to configure AUTH using env variables, that would be very handy for docker enviroments

**Actual behavior**
Ignores ELECTRS_AUTH env variable
